version: "3"
services:
 pitemp:
  build: ./pitemp
  environment:
   - PT_INTERVAL=${PITEMPINTERVAL}
   - PT_DATABASE=${PITEMPDATABASE}
   - PT_SENSOR=${PITEMPSENSORNAME}
   - PT_LOCATION=${PITEMPLOCATIONNAME}
  devices:
   - /dev/gpiomem:/dev/gpiomem
 influxdb:
  image: influxdb:latest
  volumes:
   - influxdb-storage:/var/lib/influxdb
  ports:
   - 8086:8086
  environment:
   - INFLUXDB_DB=${PITEMPDATABASE}
   - INFLUXDB_ADMIN_USER=${PITEMPADMINUSER}
   - INFLUXDB_ADMIN_PASSWORD=${PITEMPDBPASSWORD}
 grafana:
  image: grafana/grafana:latest
  volumes:
   - grafana-storage:/var/lib/grafana
   - ./provisioning:/etc/grafana/provisioning
  ports:
   - 3000:3000
  environment:
   - GF_SECURITY_ADMIN_USER=${PITEMPADMINUSER}
   - GF_SECURITY_ADMIN_PASSWORD=${PITEMPGFPASSWORD}
   - INFLUXDB_DB=${PITEMPDATABASE}
   - INFLUXDB_ADMIN_USER=${PITEMPADMINUSER}
   - INFLUXDB_ADMIN_PASSWORD=${PITEMPDBPASSWORD}
  depends_on:
   - influxdb

volumes:
 influxdb-storage:
 grafana-storage:
