version: "3"
services:
 pitemp:
  build: ./pitemp
 influxdb:
  image: influxdb:latest
  volumes:
   - influxdb-storage:/var/lib/influxdb
  ports:
   - 8086:8086
  environment:
   - INFLUXDB_DB=db0
   - INFLUXDB_ADMIN_USER=adminuser
   - INFLUXDB_ADMIN_PASSWORD=adminpassword
 grafana:
  image: grafana/grafana:latest
  volumes:
   - grafana-storage:/var/lib/grafana
  ports:
   - 3000:3000
  environment:
   - GF_SECURITY_ADMIN_USER=adminuser
   - GF_SECURITY_ADMIN_PASSWORD=adminpassword
  depends_on:
   - influxdb

volumes:
 influxdb-storage:
 grafana-storage:
