version: "3"
services:
 pitemp:
  build: ./pitemp
  volumes:
   - ./product:usr/src/app
  ports:
   - 1337:1337
 influxdb:
  image: influxdb:latest
  volumes:
   - ./influx-storage:/var/lib/influxdb
  ports:
   - 3003:3003
 grafana:
  image: grafana/grafana:latest
  volumes:
   - ./grafana:/var/lib/grafana
  ports:
   - 3000:3000
  depends_on:
   - influxdb
